# Generated by Django 5.0.6 on 2024-07-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
